### ISSUE TITLE
Messenger 

### ISSUE THREAD

**Issue by ghost** [dispxxx/leblog#4]
Ligne 37 dans handler_messenger_answer.php n'est pas en mysqli_real_escape_string ??

**Comment by dispxxx** [comment]
Putain travailles le soir si tu veux mais déranges pas les honnêtes gens
stp.

Cordialement, un français en deuil.

Octave Raimbault

**Comment by ghost** [comment]
Boulet... C'est une vrai bonne idée à GitHub d'avoir fait les alertes par mail :+1:  :+1:  :+1:

**Comment by dispxxx** [comment]
À GitHub en fait, mais en ignare comme toi dois probablement pas faire la
différence !

Octave Raimbault
